version: "3.9"   
services:
  fastapi:
    build:
      context: ./back-stt
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "8000:8000"
    command: "sh -c 'uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'"
    expose: 
      - "8000"
    volumes:
      - ./back-stt/app:/code/
    env_file: ".env"
